import React from 'react'
import {render} from 'react-dom'
import EventPropagator from 'events/EventPropagator'

import Modal from './Modal'
import Slider from 'react-slick'

import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'
// import 'style!react-responsive-carousel/lib/styles/carousel.css'

class HelpDisplayer extends React.Component {
	constructor(props) {
		super(props)
		this.state = {
			show: false

		}
	}
	componentDidMount() {
		EventPropagator.registerListener({
			eventType: "show_help",
			callback: (payload) => {
				this.setState({"show": true})
				if (payload != null)
				{
					switch (payload.slide) {
						case "about":
							this.refs.slider.slickGoTo(1)
							break;
						case "help":
							this.refs.slider.slickGoTo(0)
							break;
					}
				}
			}
		})
	}
	render() {
		return (
			<Modal isVisible={this.state.show}
				onClickHandler={() => console.log("do nothing")}>
				<div className="close_button" onClick={() => this.setState({"show": false})}></div>
				<h1>Getting started with qBible</h1>
				<div className="helpSlider">
					<Slider settings={{"dots": true, "arrows": true}} ref='slider'>
						<div className="slickslide">
							<iframe width="853" height="480" src="https://www.youtube.com/embed/9avHu4nVeCg?showinfo=0" frameBorder="0" allowFullScreen></iframe>
						</div>
						<div className="slickslide">
							<div className="information">
								<h2>The data behind qBible</h2>
								<p>
									Here are a <a href="https://www.youtube.com/watch?v=9avHu4nVeCg&index=1&list=PLIgxXpfu-c4lwsjrW14_X5bG8FodYOr9l">few videos</a> to help you get up to speed with qBible but this is the background behind the project. QBible was built by <a href="https://github.com/jcuenod">James Cuénod</a> using <a href="https://github.com/ETCBC/text-fabric/wiki">Text-Fabric</a> as a way to interact with ETCBC Hebrew data.
								</p>
								<p>
									The data that powers qBible is the <a href="https://www.godgeleerdheid.vu.nl/en/research/institutes-and-centres/eep-talstra-centre-for-bible-and-computer/index.aspx">ETCBC4 (Eep Talstra Centre for Bible and Computing)</a> linguistic database (formerly known as WIVU). The data was generated by a partnership between the German Bible Society and the Netherlands Bible society and is archived for <i>open access</i>. QBible itself is <a href="https://github.com/jcuenod/lafwebpy">open source</a>. Another way of interacting with the same data is to use <a href="https://shebanq.ancient-data.org/">SHEBANQ</a> which provides a way of building and saving queries to the data.
								</p>
								<p>
									The LXX data is derived from work especially by <a href="http://ccat.sas.upenn.edu/rak/catss.html">CCAT</a> using the work of Michael Stead in Bible Crawler who also provided the base for some work on the <a href="http://sdbh.org/">SDBH (Semantic Dictionary of Biblical Hebrew)</a> (still needing a lot of revision).
								</p>
								<p>
									The English text displayed alongside search results is that of the <a href="https://netbible.org/">NET</a>: Scripture quoted by permission. All scripture quotations, unless otherwise indicated, are taken from the <a href='http://netbible.org'>NET Bible</a>® copyright ©1996-2016 by Biblical Studies Press, L.L.C. All rights reserved.
								</p>
							</div>
						</div>
					</Slider>
				</div>
			</Modal>
		)
	}
}
export default HelpDisplayer
